import { getDictDataPage } from '@/api/system/dict/dict.data'
// 进度模板 列表配置项
export const templateTableColumns = reactive([
  {
    id: '96d3a09b-c65b-4c0a-a321-02929f535196',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '节点名称',
    code: 'nodeName',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 0,
    dictCode: null,
    defaultValue: '',
    maxLength: 30,
    placeholder: '请输入',
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: true,
    supportSort: false,
    supportFilter: false,
    sort: 1,
    options: null,
    moduleName: null
  },
  {
    id: '856c4cd8-bf0f-420d-9549-86d93f06ba7e',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '前置节点',
    code: 'preNodeCode',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 0,
    dictCode: null,
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 2,
    options: null,
    moduleName: null
  },
  // {
  //   id: "1ad9d6c6-db2b-412d-8fbb-ef865db717ea",
  //   company: "ALL",
  //   isDeleted: 0,
  //   companyName: null,
  //   recordChangeDataFlag: false,
  //   name: "部门名称",
  //   code: "depName",
  //   moduleId: "2cedfec6-a093-48b8-93a6-9dbc7bebd422",
  //   state: 1,
  //   type: 7,
  //   dictCode: null,
  //   defaultValue: null,
  //   maxLength: null,
  //   placeholder: null,
  //   listDisplay: false,
  //   required: false,
  //   edit: false,
  //   searchDisplay: false,
  //   supportSort: false,
  //   supportFilter: false,
  //   sort: 2,
  //   options: null,
  //   moduleName: null
  // },
  {
    id: '856c4cd8-bf0f-420d-9549-86d93f06ba7e',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '节点编码',
    code: 'nodeCode',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 0,
    dictCode: null,
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 3,
    options: null,
    moduleName: null
  },
  {
    id: '856c4cd8-bf0f-420d-9549-86d93f06ba7e',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '后置节点',
    code: 'nextNodeCode',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 0,
    dictCode: null,
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 4,
    options: null,
    moduleName: null
  },
  // {
  //   id: "af67e3d3-5ec9-4be5-924d-3d7bcba3eb63",
  //   company: "ALL",
  //   isDeleted: 0,
  //   companyName: null,
  //   recordChangeDataFlag: false,
  //   name: "节点顺序",
  //   code: "nodeOrder",
  //   moduleId: "2cedfec6-a093-48b8-93a6-9dbc7bebd422",
  //   state: 1,
  //   type: 1,
  //   dictCode: null,
  //   defaultValue: "1",
  //   maxLength: null,
  //   placeholder: null,
  //   listDisplay: true,
  //   required: false,
  //   edit: true,
  //   searchDisplay: false,
  //   supportSort: false,
  //   supportFilter: false,
  //   sort: 4,
  //   options: null,
  //   moduleName: null
  // },
  {
    id: 'b5f3ef0f-f805-4f80-ac73-e5b5e73fa6e3',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '基准时长',
    code: 'basisDuration',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 1,
    dictCode: null,
    defaultValue: '1',
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 5,
    options: null,
    moduleName: null
  },
  // {
  //   id: "ce63f900-3e73-49fa-8b14-525c2e2f9ea6",
  //   company: "ALL",
  //   isDeleted: 0,
  //   companyName: null,
  //   recordChangeDataFlag: false,
  //   name: "是否需要审核",
  //   code: "isExamine",
  //   moduleId: "2cedfec6-a093-48b8-93a6-9dbc7bebd422",
  //   state: 1,
  //   type: 2,
  //   dictCode: "95fe0edf-28d3-47ef-ac03-f80e8a4d9e4f",
  //   defaultValue: "0",
  //   maxLength: null,
  //   placeholder: "请选择是否需要审核",
  //   listDisplay: false,
  //   required: false,
  //   edit: true,
  //   searchDisplay: true,
  //   supportSort: false,
  //   supportFilter: false,
  //   sort: 6,
  //   options: null,
  //   moduleName: null
  // },
  {
    id: 'b4667e19-95f7-4a19-aa96-7b0a7f20e9f2',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '自动开始',
    code: 'autoStart',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 2,
    dictCode: '95fe0edf-28d3-47ef-ac03-f80e8a4d9e4f',
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: false,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 6,
    options: null,
    moduleName: null
  },
  {
    id: 'eec6fe07-ff8e-48a7-9290-34ab4e139d67',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '预警时长',
    code: 'warningDuration',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 1,
    dictCode: null,
    defaultValue: '1',
    maxLength: null,
    placeholder: null,
    listDisplay: false,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 7,
    options: null,
    moduleName: null
  },
  {
    id: '331808f6-52f0-48ca-b6c1-6714bed4cf69',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '时长单位',
    code: 'durationUnit',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 2,
    dictCode: 'e4bb3f1c-9fd8-44c5-9bde-a526785aaab8',
    defaultValue: 'day',
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 8,
    options: null,
    moduleName: null
  },
  {
    id: '32134eb2-7eea-421c-8acf-ffc7a032f9df',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '周休',
    code: 'weeklyRest',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 3,
    dictCode: '1ed1bc96-2ad1-4803-9e0f-c126ef094a9b',
    defaultValue: 'seven',
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 9,
    options: null,
    moduleName: null
  },
  {
    id: '79cae9a8-9a09-46fb-9106-66cea5c02db1',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '提交人',
    code: 'personInChargeList',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 0,
    type: 8,
    dictCode: null,
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 10,
    options: null,
    moduleName: null
  },
  {
    id: '3dba3d1c-317d-4365-9126-fa17ca070f18',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '提交人员类型',
    code: 'submitType',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 2,
    dictCode: 'f4f678f1-6b4c-49c3-b26a-7e6fcaf455bc',
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 11,
    options: null,
    moduleName: null
  },
  {
    id: '32498d6a-6594-431f-9ea2-0283aae3b5a6',
    company: 'ALL',
    isDeleted: 0,
    companyName: null,
    recordChangeDataFlag: false,
    name: '提交人',
    code: 'personInCharge',
    moduleId: '2cedfec6-a093-48b8-93a6-9dbc7bebd422',
    state: 1,
    type: 8,
    dictCode: null,
    defaultValue: null,
    maxLength: null,
    placeholder: null,
    listDisplay: true,
    required: false,
    edit: false,
    searchDisplay: false,
    supportSort: false,
    supportFilter: false,
    sort: 12,
    options: null,
    moduleName: null
  }
])
